/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Zo5MIIS7YUO
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

import DynamicCard from "../ui/customizeCard"
// import { Button } from "../ui/button"
import { CarouselPlugin } from "./home/banner/slider"
// import Link from "next/link"
import BannerText from "./home/banner/banner-text"


export function BannerSlider() {
  return (
    <div className="w-full lg:flex justify-center items-center py-12 md:py-24 lg:py-24 text-white">
      <DynamicCard className="w-[60%]">
        <BannerText />
      </DynamicCard>
      <DynamicCard width="40%" className="flex justify-center items-center">
        <CarouselPlugin />
      </DynamicCard>
    </div>
  )
}
