"use client"
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/xYHqD5MkVkT
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import TextLogo from "./logo/textLogo"
import { DropdownMenuTrigger, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"
import Image from "next/image"
import { signOut, useSession } from "next-auth/react"
import userIcon from '@/assets/userplaceholder.png'
import { useRouter } from "next/navigation"
import Swal from "sweetalert2"

export function Navigation() {
  const { data } = useSession()
  const router = useRouter()
  const handleSignOut = async () => {
    await signOut({ redirect: false }).then(() => {
      Swal.fire({
        title: 'See you!',
        text: 'Log out successful.',
        icon: 'success',
        confirmButtonText: 'Okay',
        confirmButtonColor: 'hsl(var(--main-primary-violet))'
      });
      router.push("/"); // Redirect to the home page after signing out
    });

  }


  return (
    <nav className="bg-white shadow-sm dark:bg-gray-950/90">
      <div className="w-full container mx-auto px-4">
        <div className="flex justify-between h-14 items-center">
          <TextLogo />
          <nav className="hidden md:flex gap-4">
            <Link className="font-medium flex items-center text-sm transition-colors hover:underline" href="/">
              Home
            </Link>
            <Link className="font-medium flex items-center text-sm transition-colors hover:underline" href="/dashboard">
              Dashboard
            </Link>
            <Link className="font-medium flex items-center text-sm transition-colors hover:underline" href="/about">
              About
            </Link>
            <Link className="font-medium flex items-center text-sm transition-colors hover:underline" href="#">
              Services
            </Link>
            <Link className="font-medium flex items-center text-sm transition-colors hover:underline" href="#">
              Contact
            </Link>
          </nav>
          <div className="flex items-center gap-4">
            {
              data ?
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button
                      className="rounded-full border border-gray-200 w-8 h-8 dark:border-gray-800"
                      size="icon"
                      variant="ghost"
                    >
                      <Image
                        alt="Avatar"
                        className="rounded-full"
                        height="32"
                        src={data?.user?.image ? data?.user?.image : userIcon.src}
                        style={{
                          aspectRatio: "32/32",
                          objectFit: "cover",
                        }}
                        width="32"
                      />
                      <span className="sr-only">Toggle user menu</span>
                    </Button>
                  </DropdownMenuTrigger >
                  <DropdownMenuContent align="end">
                    <DropdownMenuLabel>{data?.user?.name}</DropdownMenuLabel>
                    <DropdownMenuSeparator />
                    <DropdownMenuItem>Settings</DropdownMenuItem>
                    <DropdownMenuItem>Support</DropdownMenuItem>
                    <DropdownMenuSeparator />
                    <DropdownMenuItem onClick={handleSignOut}>Logout</DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>

                :
                <>
                  <Link href="/signup">
                    <Button size="sm">Sign up</Button>
                  </Link>
                  <Link href="/login">
                    <Button size="sm" variant="outline">
                      Log in
                    </Button>
                  </Link>
                </>
            }
          </div>
        </div>
      </div>
    </nav>
  )
}

function MountainIcon(props: {}) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      className="h-6 w-6"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}
