"use client"
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/xYHqD5MkVkT
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import TextLogo from "./logo/textLogo"
import { useSession } from "next-auth/react"
import { useRouter, usePathname } from "next/navigation"
import SimpleLogin from "./simpleLogin/simpleLogin"
import { useEffect, useState } from "react"
import SimpleSignUp from "./simpleLogin/simpleSignup"
import UserIconDropdown from "./userDropdownNav/userIconDropdown"

export function Navigation() {
  const { data } = useSession()
  const router = useRouter()
  const pathname = usePathname()
  const [showHideLogin, setShowHideLogin] = useState(false)
  const [showHideSignUp, setShowHideSignUp] = useState(false)
  const session = useSession()

  useEffect(() => {
    if (session.status === 'authenticated') {
      setShowHideLogin(true);
      setShowHideSignUp(false)
    }
  }, [session])


  const handleLoginOpen = () => {
    setShowHideLogin(!showHideLogin)
  }
  const handleSignUpOpen = () => {
    setShowHideSignUp(!showHideSignUp)
  }


  type NavMenu = {
    id: string | number;
    name: string;
    path: string;
  }

  const menu: NavMenu[] = [
    { id: 1, name: 'Home', path: '/' },
    { id: 2, name: 'All courses', path: '/allcourses' },
    { id: 3, name: 'Services', path: '/services' },
    { id: 4, name: 'About', path: '/about' },
    { id: 5, name: 'Contact', path: '/contact' },
  ]


  const isActive = (path: string) => pathname === path;

  return (
    <nav className="bg-white overflow-hidden max-w-[100vw] shadow-sm dark:bg-gray-950/90">
      <div className="w-full container mx-auto px-4">
        <div className="flex overflow-hidden justify-between h-14 items-center">
          <TextLogo />
          <nav className="hidden md:flex gap-4">
            {menu.map((link) => <Link href={link.path} key={link.id} className={`font-medium flex items-center text-sm transition-colors relative  ${isActive(link.path) ?
              ` before:content-[''] before:absolute before:rounded-full before:-bottom-1 before:left-0 before:w-full before:h-1 before:bg-main-primary-violet before:duration-200 before:ease-in-out`
              :
              `before:content-[''] before:absolute before:rounded-full before:-bottom-1 before:left-0 before:w-full before:h-1 before:bg-main-primary-violet hover:before:scale-x-100 before:scale-x-0 before:origin-right hover:before:origin-left before:transition-transform before:duration-200 before:ease-in-out`}`}>
              {link.name}
            </Link>)}
          </nav>
          <div className="flex overflow-hidden items-center gap-4">
            {data ? (
              <UserIconDropdown />
            ) : (
              <>
                <Button onClick={handleSignUpOpen} size="sm">Sign up</Button>
                <Button onClick={handleLoginOpen} size="sm" variant="outline">
                  Log in
                </Button>
                <div className={`absolute lg:fixed z-50 top-0 right-0 duration-300 transform ${showHideSignUp ? '' : '-mx-[100vw] md:-mx-[510px] 2xl:-mx-[810px]'}`}>
                  <SimpleSignUp handleOpen={handleSignUpOpen} />
                </div>
                <div className={`absolute lg:fixed z-50 top-0 right-0 duration-300 transform ${showHideLogin ? '' : '-mx-[100vw] md:-mx-[510px] 2xl:-mx-[810px]'}`}>
                  <SimpleLogin handleOpen={handleLoginOpen} />
                </div>
              </>
            )}
          </div>
        </div>
      </div>

    </nav>
  )
}


