/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/0uB7Q9lWUU1
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import Image from "next/image"


export function VideoContainer() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container space-y-12 px-4 md:px-6">

        <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
          <div className="group relative overflow-hidden rounded-lg border border-gray-200 dark:border-gray-800">
            <Link className="absolute inset-0 z-10" href="#">
              <span className="sr-only">View property</span>
            </Link>
            <Image
              alt="Property 1"
              className="h-60 w-full object-cover object-center transition-all duration-300 group-hover:scale-105"
              height={400}
              src="/placeholder.svg"
              style={{
                aspectRatio: "600/400",
                objectFit: "cover",
              }}
              width={600}
            />
            <div className="p-4">
              <h3 className="text-lg font-semibold">Luxury Penthouse</h3>
              <div className="mt-2 flex items-center justify-between">
                <div className="flex items-center space-x-2">
                  <BedIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                  <span className="text-sm text-gray-500 dark:text-gray-400">3 Beds</span>
                </div>
                <div className="flex items-center space-x-2">
                  <BathIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                  <span className="text-sm text-gray-500 dark:text-gray-400">2 Baths</span>
                </div>
                <div className="flex items-center space-x-2">
                  <RulerIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                  <span className="text-sm text-gray-500 dark:text-gray-400">2,500 sqft</span>
                </div>
              </div>
              <div className="mt-4 flex items-center justify-between">
                <span className="text-lg font-semibold">$1,200,000</span>
                <Button size="sm">View</Button>
              </div>
            </div>
          </div>
          <div className="group relative overflow-hidden rounded-lg border border-gray-200 dark:border-gray-800">
            <Link className="absolute inset-0 z-10" href="#">
              <span className="sr-only">View property</span>
            </Link>
            <Image
              alt="Property 2"
              className="h-60 w-full object-cover object-center transition-all duration-300 group-hover:scale-105"
              height={400}
              src="/placeholder.svg"
              style={{
                aspectRatio: "600/400",
                objectFit: "cover",
              }}
              width={600}
            />
            <div className="p-4">
              <h3 className="text-lg font-semibold">Modern Townhouse</h3>
              <div className="mt-2 flex items-center justify-between">
                <div className="flex items-center space-x-2">
                  <BedIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                  <span className="text-sm text-gray-500 dark:text-gray-400">2 Beds</span>
                </div>
                <div className="flex items-center space-x-2">
                  <BathIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                  <span className="text-sm text-gray-500 dark:text-gray-400">2.5 Baths</span>
                </div>
                <div className="flex items-center space-x-2">
                  <RulerIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                  <span className="text-sm text-gray-500 dark:text-gray-400">1,800 sqft</span>
                </div>
              </div>
              <div className="mt-4 flex items-center justify-between">
                <span className="text-lg font-semibold">$850,000</span>
                <Button size="sm">View</Button>
              </div>
            </div>
          </div>
          <div className="group relative overflow-hidden rounded-lg border border-gray-200 dark:border-gray-800">
            <Link className="absolute inset-0 z-10" href="#">
              <span className="sr-only">View property</span>
            </Link>
            <Image
              alt="Property 3"
              className="h-60 w-full object-cover object-center transition-all duration-300 group-hover:scale-105"
              height={400}
              src="/placeholder.svg"
              style={{
                aspectRatio: "600/400",
                objectFit: "cover",
              }}
              width={600}
            />
            <div className="p-4">
              <h3 className="text-lg font-semibold">Cozy Cottage</h3>
              <div className="mt-2 flex items-center justify-between">
                <div className="flex items-center space-x-2">
                  <BedIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                  <span className="text-sm text-gray-500 dark:text-gray-400">2 Beds</span>
                </div>
                <div className="flex items-center space-x-2">
                  <BathIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                  <span className="text-sm text-gray-500 dark:text-gray-400">1 Bath</span>
                </div>
                <div className="flex items-center space-x-2">
                  <RulerIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                  <span className="text-sm text-gray-500 dark:text-gray-400">1,200 sqft</span>
                </div>
              </div>
              <div className="mt-4 flex items-center justify-between">
                <span className="text-lg font-semibold">$450,000</span>
                <Button size="sm">View</Button>
              </div>
            </div>
          </div>
          <div className="group relative overflow-hidden rounded-lg border border-gray-200 dark:border-gray-800">
            <Link className="absolute inset-0 z-10" href="#">
              <span className="sr-only">View property</span>
            </Link>
            <Image
              alt="Property 4"
              className="h-60 w-full object-cover object-center transition-all duration-300 group-hover:scale-105"
              height={400}
              src="/placeholder.svg"
              style={{
                aspectRatio: "600/400",
                objectFit: "cover",
              }}
              width={600}
            />
            <div className="p-4">
              <h3 className="text-lg font-semibold">Beachfront Villa</h3>
              <div className="mt-2 flex items-center justify-between">
                <div className="flex items-center space-x-2">
                  <BedIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                  <span className="text-sm text-gray-500 dark:text-gray-400">4 Beds</span>
                </div>
                <div className="flex items-center space-x-2">
                  <BathIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                  <span className="text-sm text-gray-500 dark:text-gray-400">3 Baths</span>
                </div>
                <div className="flex items-center space-x-2">
                  <RulerIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                  <span className="text-sm text-gray-500 dark:text-gray-400">3,000 sqft</span>
                </div>
              </div>
              <div className="mt-4 flex items-center justify-between">
                <span className="text-lg font-semibold">$2,500,000</span>
                <Button size="sm">View</Button>
              </div>
            </div>
          </div>
        </div>
        <div className="flex justify-center">
          <Button>View More Properties</Button>
        </div>
      </div>
    </section>
  )
}

function BathIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M9 6 6.5 3.5a1.5 1.5 0 0 0-1-.5C4.683 3 4 3.683 4 4.5V17a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-5" />
      <line x1="10" x2="8" y1="5" y2="7" />
      <line x1="2" x2="22" y1="12" y2="12" />
      <line x1="7" x2="7" y1="19" y2="21" />
      <line x1="17" x2="17" y1="19" y2="21" />
    </svg>
  )
}


function BedIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 4v16" />
      <path d="M2 8h18a2 2 0 0 1 2 2v10" />
      <path d="M2 17h20" />
      <path d="M6 8v9" />
    </svg>
  )
}


function RulerIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21.3 15.3a2.4 2.4 0 0 1 0 3.4l-2.6 2.6a2.4 2.4 0 0 1-3.4 0L2.7 8.7a2.41 2.41 0 0 1 0-3.4l2.6-2.6a2.41 2.41 0 0 1 3.4 0Z" />
      <path d="m14.5 12.5 2-2" />
      <path d="m11.5 9.5 2-2" />
      <path d="m8.5 6.5 2-2" />
      <path d="m17.5 15.5 2-2" />
    </svg>
  )
}
